### ISSUE TITLE
README install instructions

### ISSUE THREAD

**Issue by jwoertink** [sol-vin/libsunvox#1]
It looks like the README says run `rsrc/install.sh`, but the `install.sh` seems to be at the top level.

**Comment by RespiteSage** [comment]
Also, the `install.sh` is incomplete. Because of the `shard.lock` in `rsrc/examples/crystal/`, you need to run `shards update`, and you also need to `mkdir -p lib` after `cd`ing there so that the soft link is correctly created. I'd like to put in a PR, but I still couldn't quite figure out how to get the example working.

I realize this is a slightly different issue than the one given above. Should I split off a separate issue for the `install.sh` modifications?

**Comment by jwoertink** [comment]
@RespiteSage Yeah, I'd say so. I wasn't able to actually install. I had to remove the sudo, and change it to copy to `/usr/local/bin`, and then I got a lot of other errors. I figure this library is probably still in the works, so it may be a bit early to start opening up a ton of issues. Definitely a cool sounding project though!

**Comment by sol-vin** [comment]
My bad I'll make those changes. I got this to work on the current Ubuntu, the install script was the only way I could reliably do it. Take a look through https://github.com/sol-vin/libsunvox/tree/master/rsrc/linux, it has all the `.so` files for https://github.com/sol-vin/libsunvox/blob/master/src/libsunvox.cr#L2 to latch onto. If anyone has a better way of doing this I'd be happy to change it, I'm honestly not happy with how this works either.

**Comment by sol-vin** [comment]
Fixed the readme issue in https://github.com/sol-vin/libsunvox/commit/09df4524208383fdc3419e09d11a6561812eaf28. Will keep this open for other suggestions on how to do the `.so` installation better.

**Comment by sol-vin** [comment]
> 
> 
> Also, the `install.sh` is incomplete. Because of the `shard.lock` in `rsrc/examples/crystal/`, you need to run `shards update`, and you also need to `mkdir -p lib` after `cd`ing there so that the soft link is correctly created. I'd like to put in a PR, but I still couldn't quite figure out how to get the example working.
> 
> I realize this is a slightly different issue than the one given above. Should I split off a separate issue for the `install.sh` modifications?

Let me know if https://github.com/sol-vin/libsunvox/commit/8fbd92b7ea76ab012cde41732233d56c71e94ba7 fixes it for you.

**Comment by RespiteSage** [comment]
I'm running into `ld` issues now. I think `/usr/lib` may not be in my `ld` include path, but I'm going to figure that out.

UPDATE: I was able to fix the `ld` issue by renaming the shared object file to `libsunvox.so`.

**Comment by sol-vin** [comment]
Thanks for the update. I think I may have fixed it this time around. Turns out I had made a symbolic link from `/lib/sunvox.so -> /usr/lib/libsunvox.so` that I forgot to add into the install script. Hopefully that will fix the issue for most people. Thanks for the help!
